variables:
  service_name: gp-connect-user-permissions
  short_service_name: gcup
  service_base_path: gp-connect/patient-facing/user-permissions
  pr_number: ${{ split(variables['Build.SourceBranch'], '/')[2] }}
