#!/bin/bash

# Build the examples into the spec via speccy
speccy resolve ../specification/gp-connect-user-permissions.yaml -o ../specification/speccy-output.yaml

# Convert the full spec into a postman collection
openapi2postmanv2 -s ../specification/speccy-output.yaml -o ../specification/postman-collection.json -p -O folderStrategy=Tags,includeAuthInfoInExample=false
#
## Clean up the file generated by speccy
rm ../specification/speccy-output.yaml
